sudo: false
language: rust
matrix:
  fast_finish: true
  allow_failures:
    - name: rust beta
    - name: coverage
  include:
    - name: rust stable
      rust: stable

    - name: rust beta
      rust: beta

    - name: rust nightly
      rust: nightly
      script:
        - cargo test --release --features simd --no-run
        - strip target/release/hld
        - upx --ultra-brute --lzma target/release/hld
        - cargo test --release --features simd
        - mv target/release/hld target/release/hld-`target/release/hld --version | sed -e 's/hld //'`-`uname -m`
      addons:
        apt:
          packages:
            - upx

    - name: fmt
      rust: stable
      install:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt -- --check

    - name: clippy
      rust: stable
      install:
        - rustup component add clippy-preview
      script:
        - cargo clippy -- -D clippy

    - name: coverage
      rust: stable
      install:
        - curl -L https://github.com/SimonKagstrom/kcov/archive/master.tar.gz | tar xvz
        - cd kcov-master && cmake . && make -j && sudo make install
      script:
        - echo $PATH
        - which kcov
        - cargo test --features kcov -- --test-threads 1
        - bash <(curl -s https://codecov.io/bash)
      addons: # required for kcov
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - cmake

script:
  - cargo test

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work - see https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo
  apt: true
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
  # But don't cache the cargo registry
  - rm -rf /home/travis/.cargo/registry

notifications:
  email:
    on_success: never

deploy:
  provider: releases
  api_key:
    secure: OnnKatnWDoUegCSgU/7m1HGgv49YbCUnXZYfFeDrf7ILaY1n0NXZkSlbrDt3KMepihUssE74q3DGx8YeqQ50eZfBFyOPQCWAwmzTBlDo8puj9/07bkfTLC9uhGS11Y+lTU6OIc4jZp1UbPBOTH3nAC73xgnvN/yBvo7Gf52WR11oiiFQ0yw4WoHMb36ccBhGne/TuftVup4y2/zcJ4KoIVugyZENW6VkCp2EbCcCvSfNM8VzMYt4b9Dek1pLAYNdrU9/sdOJWbYiHYTDPA2cROo1Qo4xH2nlVPYoEcc8qK5ifxxYJDBHDVy4yWXFW7eOHlaTP30ypdbKS0N1zWo39LIfwCkT7EwuQNsomZvQ4T/HUjuhZa2af/+6yePcv9ekKlqAzRQq1q/3GHwd7Iz2KSAkJCxGIYLCq0KbJDto3brzYfZMDA8kUBzqKSnwJktnQBdfN0g7z1iMhvgikZ2Z57Mjb3cN8MF5a+X+sFOXWm+J/IouR7QZm8+ZjWXUGr/864gWo2ZzymlCYb2eYMghCJqp5g/YieEGMZjVnCexFmhHiJLX6/YfuAC3gshaHHNRuphRiAem+M4/uBm5fFZt2aOlzvC8r5h+ids41hmvJcAyVE+EDsZ/c9WNKLHFR/bK4yxrxYfHM1qvDZPQ869k+SchlT+/3DVKmFeuMGd3nzs=
  file_glob: true
  file: target/release/hld-*-*
  skip_cleanup: true
  draft: true
  on:
    repo: glehmann/hld
    rust: nightly
    # tags: true
