sudo: false
language: rust
env: # required for allow_failures
matrix:
  fast_finish: true
  allow_failures:
    - name: rust beta
    - name: rust nightly
  include:
    - name: rust stable
      rust: stable

    - name: rust beta
      rust: beta

    - name: rust nightly
      rust: nightly

    - name: fmt
      rust: stable
      install:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt -- --check

    - name: warnings
      rust: stable
      env: RUSTFLAGS="-D warnings"
      script:
        - cargo check --tests

    - name: clippy
      rust: stable
      install:
        - rustup component add clippy-preview
      script:
        - cargo clippy -- -D clippy

script:
- cargo test --verbose

branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

cache:
  apt: true
  cargo: true
before_cache:
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never