sudo: false
language: rust
matrix:
  fast_finish: true
  allow_failures:
    - name: rust beta
    - name: rust nightly
  include:
    - name: rust stable
      rust: stable
      sudo: required # travis-ci/travis-ci#9061
      before_script:
        - cargo install cargo-update || echo "cargo-update already installed"
        - cargo install cargo-travis || echo "cargo-travis already installed"
        - cargo install-update -a
      script:
        - |
          cargo build --verbose &&
          cargo coverage --verbose &&
          bash <(curl -s https://codecov.io/bash) -s target/kcov
      addons: # required for kcov
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - cmake

    - name: rust beta
      rust: beta

    - name: rust nightly
      rust: nightly

    - name: fmt
      rust: stable
      install:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt -- --check

    # - name: warnings
    #   rust: stable
    #   env: RUSTFLAGS="-D warnings"
    #   script:
    #     - cargo check --tests

    - name: clippy
      rust: stable
      install:
        - rustup component add clippy-preview
      script:
        - cargo clippy -- -D clippy

script:
- cargo test --verbose

branches:
  only:
  # Release tags
  - /^v\d+\.\d+\.\d+.*$/
  - master

cache:
  apt: true
  cargo: true
before_cache:
# Travis can't cache files that are not readable by "others"
- chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never