[package]
name = "hld"
version = "0.1.0"
authors = ["Gaëtan Lehmann <gaetan.lehmann@gmail.com>"]

[dependencies]
sha1 = {version = "0.6.0", features = ["serde"]}
structopt = "0.2"
log = "0.4.6"
loggerv = "0.7.1"
glob = "0.2.11"
serde_json = "1.0.33"
fs2 = "0.4.3"
