[package]
name = "hld"
version = "0.1.0"
authors = ["Gaëtan Lehmann <gaetan.lehmann@gmail.com>"]

[dependencies]
structopt = "0.2"
log = { version = "0.4", features = ["std"] }
glob = "0.2.11"
fs2 = "0.4.3"
rayon = "1.0.3"
num_cpus = "1.9.0"
maplit = "1.0.1"
ansi_term = "0.11.0"
atty = "0.2.11"
custom_error = "1.3.0"
bincode = "1.0.1"
blake2-rfc = "0.2.18"
app_dirs = "1.2.1"

[dev-dependencies]
assert_cmd = "0.10.2"
predicates = "1.0.0"
assert_fs = "0.10.0"
lipsum = "0.6.0"
